name: 自动构建发布

on:
  workflow_dispatch: 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: 代码拉取
      uses: actions/checkout@v2

   - name: 初始化环境
      run: |
        chmod +x ./.devcontainer/scripts/init.sh
        ./.devcontainer/scripts/init.sh

    - name: Release
      run: |
        chmod +x ./release.sh
        ./release.sh      

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: 登录到docker
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

 
